bedFolder="/groups/price/farhad/Data/GTEx/v6/95Causal/bed/5casualQuan/"
LDSCPath="/home/fh80/Code/LDSC/ldsc/"
annotationsName="eQTL_CAVIAR_GTEx_v6_5causal/"
annotationsFolder="/groups/price/farhad/Data/Annotations/"
outFolder="/groups/price/farhad/Results/LDSC_eQTL_GTEx_CAVIAR_5casaul_v6_7Nov2016_LD/"
summaryFolder="/groups/price/farhad/Data/SummaryStatistics/"
